CREATE TABLE LISTA_PLAC_USERS
(
  ID NUMBER(5) NOT NULL,
  EMPLOYEE_ID NUMBER(5) NOT NULL,
  EMAIL VARCHAR2(30) NOT NULL,
  PASSWORD VARCHAR2(30) NOT NULL

);

--ADD PRIMARY KEY

ALTER TABLE LISTA_PLAC_USERS ADD
(
 CONSTRAINT place_users_pk PRIMARY KEY (ID);
 CONSTRAINT place_users_fk FOREIGN KEY (EMPLOYEE_ID) REFERENCES LISTA_PLAC(ID)
);

CREATE SEQUENCE place_users_seq START WITH 1;

