--CREATE TABLE--
CREATE TABLE LISTA_PLAC
(
  ID NUMBER(5) NOT NULL,
  IMIE VARCHAR(8) NOT NULL,
  NAZWISKO VARCHAR(8) NOT NULL,
  PENSJA_ZASADNICZA FLOAT(5) NOT NULL,
  PREMIA_MOTYWACYJNA FLOAT(4) NOT NULL,
  PREMIA_UZ_MIES_PR_STYCZEN FLOAT(3) NOT NULL,
  PREMIA_UZ_MIES_PR_LUTY FLOAT(3) NOT NULL,
  PREMIA_UZ_MIES_PR_MARZEC FLOAT(3) NOT NULL,
  PREMIA_UZ_MIES_PR_KWIECIEN FLOAT(3) NOT NULL,
  PREMIA_UZ_MIES_PR_MAJ FLOAT(3) NOT NULL,
  PREMIA_UZ_MIES_PR_CZERWIEC FLOAT(3) NOT NULL,
  PREMIA_UZ_MIES_PR_LIPIEC FLOAT(3) NOT NULL,
  PREMIA_UZ_MIES_PR_SIERPIEN FLOAT(3) NOT NULL,
  PREMIA_UZ_MIES_PR_WRZESIEN FLOAT(3) NOT NULL,
  PREMIA_UZ_MIES_PR_PAZDZIERNIK FLOAT(3) NOT NULL,
  PREMIA_UZ_MIES_PR_LISTOPAD FLOAT(3) NOT NULL,
  PREMIA_UZ_MIES_PR_GRUDZIEN FLOAT(3) NOT NULL,
  PREMIA_UZ_MIES_WA_STYCZEN  FLOAT(5) NOT NULL,
  PREMIA_UZ_MIES_WA_LUTY  FLOAT(5) NOT NULL,
  PREMIA_UZ_MIES_WA_MARZEC FLOAT(5) NOT NULL,
  PREMIA_UZ_MIES_WA_KWIECIEN FLOAT(5) NOT NULL,
  PREMIA_UZ_MIES_WA_MAJ  FLOAT(5) NOT NULL,
  PREMIA_UZ_MIES_WA_CZERWIEC FLOAT(5) NOT NULL,
  PREMIA_UZ_MIES_WA_LIPIEC  FLOAT(5) NOT NULL,
  PREMIA_UZ_MIES_WA_SIERPIEN FLOAT(5) NOT NULL,
  PREMIA_UZ_MIES_WA_WRZESIEN FLOAT(5) NOT NULL,
  PREMIA_UZ_MIES_WA_PAZDZIERNIK FLOAT(5) NOT NULL,
  PREMIA_UZ_MIES_WA_LISTOPAD FLOAT(5) NOT NULL,
  PREMIA_UZ_MIES_WA_GRUDZIEN FLOAT(5) NOT NULL,
  PREMIA_CAL_MIES_STY FLOAT(5) NOT NULL,
  PREMIA_CAL_MIES_LUT FLOAT(5) NOT NULL,
  PREMIA_CAL_MIES_MAR FLOAT(5) NOT NULL,
  PREMIA_CAL_MIES_KWI FLOAT(5) NOT NULL,
  PREMIA_CAL_MIES_MAI FLOAT(5) NOT NULL,
  PREMIA_CAL_MIES_CZE FLOAT(5) NOT NULL,
  PREMIA_CAL_MIES_LIP FLOAT(5) NOT NULL,
  PREMIA_CAL_MIES_SIE FLOAT(5) NOT NULL,
  PREMIA_CAL_MIES_WRZ FLOAT(5) NOT NULL,
  PREMIA_CAL_MIES_PAZ FLOAT(5) NOT NULL,
  PREMIA_CAL_MIES_LIS FLOAT(5) NOT NULL,
  PREMIA_CAL_MIES_GRU FLOAT(5) NOT NULL,
  PENSJA_CAL_MIES_STY FLOAT(5) NOT NULL,
  PENSJA_CAL_MIES_LUT FLOAT(5) NOT NULL,
  PENSJA_CAL_MIES_MAR FLOAT(5) NOT NULL,
  PENSJA_CAL_MIES_KWI FLOAT(5) NOT NULL,
  PENSJA_CAL_MIES_MAI FLOAT(5) NOT NULL,
  PENSJA_CAL_MIES_CZE FLOAT(5) NOT NULL,
  PENSJA_CAL_MIES_LIP FLOAT(5) NOT NULL,
  PENSJA_CAL_MIES_SIE FLOAT(5) NOT NULL,
  PENSJA_CAL_MIES_WRZ FLOAT(5) NOT NULL,
  PENSJA_CAL_MIES_PAZ FLOAT(5) NOT NULL,
  PENSJA_CAL_MIES_LIS FLOAT(5) NOT NULL,
  PENSJA_CAL_MIES_GRU FLOAT(5) NOT NULL,
  PENSJA_MINIMALNA FLOAT(5) ,
  PENSJA_MAKSYMALNA FLOAT(5) ,
  PENSJA_SREDNIA FLOAT(5) ,
  PREMIA_MINIMALNA FLOAT(5) ,
  PREMIA_MAKSYMALNA FLOAT(5),
  PREMIA_SREDNIA FLOAT(5)

);

--ADD PRIMARY KEY

ALTER TABLE PLACE ADD
(
 CONSTRAINT place_pk PRIMARY KEY (ID)
);

CREATE SEQUENCE place_pk START_WITH 1;