CREATE OR REPLACE PACKAGE PLACE
IS

PROCEDURE WYPELNIJ_LISTE_PLAC;
PROCEDURE WYCZYSC_LISTE PLAC;

END PLACE;

CREATE OR REPLACE PACKAGE BODY PLACE
IS

PROCEDURE WYPELNIJ_LISTE_PLAC
IS

BEGIN


        DECLARE PENSJA_ZASADNICZA_VALUE NUMBER := DBMS_RANDOM.VALUE(LOW => 3000, HIGH => 10000);
        DECLARE IMIE_STRING VARCHAR(4) := DBMS_RANDOM.STRING('A', 4);
        IMIE_STRING := SUBSTR(IMIE_STRING, 4, 4)
        DECLARE NAZWISKO_STRING VARCHAR(8) := DBMS_RANDOM.STRING('A', 8);
        NAZWISKO_STRING := SUBSTR(NAZWISKO_STRING, 4, 4)
        DECLARE PREMIA_MOTYWACYJNA_VALUE FLOAT := (PENSJA_ZASADNICZA*10)/100;
        DECLARE PREMIA_UZN_MIES_PROC_STY_VAL NUMBER := DBMS_RANDOM.VALUE(LOW => 0, HIGH => 20);
        DECLARE PREMIA_UZN_MIES_PROC_LUT_VAL NUMBER := DBMS_RANDOM.VALUE(LOW => 0, HIGH => 20);
        DECLARE PREMIA_UZN_MIES_PROC_MAR_VAL NUMBER := DBMS_RANDOM.VALUE(LOW => 0, HIGH => 20);
        DECLARE PREMIA_UZN_MIES_PROC_KWI_VAL NUMBER := DBMS_RANDOM.VALUE(LOW => 0, HIGH => 20);
        DECLARE PREMIA_UZN_MIES_PROC_MAI_VAL NUMBER := DBMS_RANDOM.VALUE(LOW => 0, HIGH => 20);
        DECLARE PREMIA_UZN_MIES_PROC_CZE_VAL NUMBER := DBMS_RANDOM.VALUE(LOW => 0, HIGH => 20);
        DECLARE PREMIA_UZN_MIES_PROC_LIP_VAL NUMBER := DBMS_RANDOM.VALUE(LOW => 0, HIGH => 20);
        DECLARE PREMIA_UZN_MIES_PROC_SIE_VAL NUMBER := DBMS_RANDOM.VALUE(LOW => 0, HIGH => 20);
        DECLARE PREMIA_UZN_MIES_PROC_WRZ_VAL NUMBER := DBMS_RANDOM.VALUE(LOW => 0, HIGH => 20);
        DECLARE PREMIA_UZN_MIES_PROC_PAZ_VAL NUMBER := DBMS_RANDOM.VALUE(LOW => 0, HIGH => 20);
        DECLARE PREMIA_UZN_MIES_PROC_LIS_VAL NUMBER := DBMS_RANDOM.VALUE(LOW => 0, HIGH => 20);
        DECLARE PREMIA_UZN_MIES_PROC_GRU_VAL NUMBER := DBMS_RANDOM.VALUE(LOW => 0, HIGH => 20);
        DECLARE PREMIA_UZN_MIES_STY_VAL NUMBER := ROUND((PENSJA_ZASADNICZA_VALUE * PREMIA_UZN_MIES_PROC_STY_VAL)/100);
        DECLARE PREMIA_UZN_MIES_LUT_VAL NUMBER := ROUND((PENSJA_ZASADNICZA_VALUE * PREMIA_UZN_MIES_PROC_LUT_VAL)/100);
        DECLARE PREMIA_UZN_MIES_MAR_VAL NUMBER := ROUND((PENSJA_ZASADNICZA_VALUE * PREMIA_UZN_MIES_PROC_MAR_VAL)/100);
        DECLARE PREMIA_UZN_MIES_KWI_VAL NUMBER := ROUND((PENSJA_ZASADNICZA_VALUE * PREMIA_UZN_MIES_PROC_KWI_VAL)/100);
        DECLARE PREMIA_UZN_MIES_MAI_VAL NUMBER := ROUND((PENSJA_ZASADNICZA_VALUE * PREMIA_UZN_MIES_PROC_MAI_VAL)/100);
        DECLARE PREMIA_UZN_MIES_CZE_VAL NUMBER := ROUND((PENSJA_ZASADNICZA_VALUE * PREMIA_UZN_MIES_PROC_CZE_VAL)/100);
        DECLARE PREMIA_UZN_MIES_LIP_VAL NUMBER := ROUND((PENSJA_ZASADNICZA_VALUE * PREMIA_UZN_MIES_PROC_LIP_VAL)/100);
        DECLARE PREMIA_UZN_MIES_SIE_VAL NUMBER := ROUND((PENSJA_ZASADNICZA_VALUE * PREMIA_UZN_MIES_PROC_SIE_VAL)/100);
        DECLARE PREMIA_UZN_MIES_WRZ_VAL NUMBER := ROUND((PENSJA_ZASADNICZA_VALUE * PREMIA_UZN_MIES_PROC_WRZ_VAL)/100);
        DECLARE PREMIA_UZN_MIES_PAZ_VAL NUMBER := ROUND((PENSJA_ZASADNICZA_VALUE * PREMIA_UZN_MIES_PROC_PAZ_VAL)/100);
        DECLARE PREMIA_UZN_MIES_LIS_VAL NUMBER := ROUND((PENSJA_ZASADNICZA_VALUE * PREMIA_UZN_MIES_PROC_LIS_VAL)/100);
        DECLARE PREMIA_UZN_MIES_GRU_VAL NUMBER := ROUND((PENSJA_ZASADNICZA_VALUE * PREMIA_UZN_MIES_PROC_GRU_VAL)/100);
        DECLARE PREMIA_CAL_MIES_STY_VAL FLOAT := PREMIA_MOTYWACYJNA_VALUE + PREMIA_UZN_MIES_STY_VAL;
        DECLARE PREMIA_CAL_MIES_LUT_VAL FLOAT := PREMIA_MOTYWACYJNA_VALUE + PREMIA_UZN_MIES_LUT_VAL;
        DECLARE PREMIA_CAL_MIES_MAR_VAL FLOAT := PREMIA_MOTYWACYJNA_VALUE + PREMIA_UZN_MIES_MAR_VAL;
        DECLARE PREMIA_CAL_MIES_KWI_VAL FLOAT := PREMIA_MOTYWACYJNA_VALUE + PREMIA_UZN_MIES_KWI_VAL;
        DECLARE PREMIA_CAL_MIES_MAI_VAL FLOAT := PREMIA_MOTYWACYJNA_VALUE + PREMIA_UZN_MIES_MAI_VAL;
        DECLARE PREMIA_CAL_MIES_CZE_VAL FLOAT := PREMIA_MOTYWACYJNA_VALUE + PREMIA_UZN_MIES_CZE_VAL;
        DECLARE PREMIA_CAL_MIES_LIP_VAL FLOAT := PREMIA_MOTYWACYJNA_VALUE + PREMIA_UZN_MIES_LIP_VAL;
        DECLARE PREMIA_CAL_MIES_SIE_VAL FLOAT := PREMIA_MOTYWACYJNA_VALUE + PREMIA_UZN_MIES_SIE_VAL;
        DECLARE PREMIA_CAL_MIES_WRZ_VAL FLOAT := PREMIA_MOTYWACYJNA_VALUE + PREMIA_UZN_MIES_WRZ_VAL;
        DECLARE PREMIA_CAL_MIES_PAZ_VAL FLOAT := PREMIA_MOTYWACYJNA_VALUE + PREMIA_UZN_MIES_PAZ_VAL;
        DECLARE PREMIA_CAL_MIES_LIS_VAL FLOAT := PREMIA_MOTYWACYJNA_VALUE + PREMIA_UZN_MIES_LIS_VAL;
        DECLARE PREMIA_CAL_MIES_GRU_VAL FLOAT := PREMIA_MOTYWACYJNA_VALUE + PREMIA_UZN_MIES_GRU_VAL;
        DECLARE PENSJA_CAL_MIES_STY_VAL FLOAT := PENSJA_ZASADNICZA_VALUE + PREMIA_CAL_MIES_STY_VAL;
        DECLARE PENSJA_CAL_MIES_LUT_VAL FLOAT := PENSJA_ZASADNICZA_VALUE + PREMIA_CAL_MIES_LUT_VAL;
        DECLARE PENSJA_CAL_MIES_MAR_VAL FLOAT := PENSJA_ZASADNICZA_VALUE + PREMIA_CAL_MIES_MAR_VAL;
        DECLARE PENSJA_CAL_MIES_KWI_VAL FLOAT := PENSJA_ZASADNICZA_VALUE + PREMIA_CAL_MIES_KWI_VAL;
        DECLARE PENSJA_CAL_MIES_MAI_VAL FLOAT := PENSJA_ZASADNICZA_VALUE + PREMIA_CAL_MIES_MAI_VAL;
        DECLARE PENSJA_CAL_MIES_CZE_VAL FLOAT := PENSJA_ZASADNICZA_VALUE + PREMIA_CAL_MIES_CZE_VAL;
        DECLARE PENSJA_CAL_MIES_LIP_VAL FLOAT := PENSJA_ZASADNICZA_VALUE + PREMIA_CAL_MIES_LIP_VAL;
        DECLARE PENSJA_CAL_MIES_SIE_VAL FLOAT := PENSJA_ZASADNICZA_VALUE + PREMIA_CAL_MIES_SIE_VAL;
        DECLARE PENSJA_CAL_MIES_WRZ_VAL FLOAT := PENSJA_ZASADNICZA_VALUE + PREMIA_CAL_MIES_WRZ_VAL;
        DECLARE PENSJA_CAL_MIES_PAZ_VAL FLOAT := PENSJA_ZASADNICZA_VALUE + PREMIA_CAL_MIES_PAZ_VAL;
        DECLARE PENSJA_CAL_MIES_LIS_VAL FLOAT := PENSJA_ZASADNICZA_VALUE + PREMIA_CAL_MIES_LIS_VAL;
        DECLARE PENSJA_CAL_MIES_GRU_VAL FLOAT := PENSJA_ZASADNICZA_VALUE + PREMIA_CAL_MIES_GRU_VAL;

        INSERT INTO LISTA_PLAC(
            IMIE,
            NAZWISKO,
            PENSJA_ZASADNICZA,
            PREMIA_MOTYWACYJNA,
            PREMIA_UZ_MIES_PR_STYCZEN,
            PREMIA_UZ_MIES_PR_LUTY,
            PREMIA_UZ_MIES_PR_MARZEC,
            PREMIA_UZ_MIES_PR_KWIECIEN,
            PREMIA_UZ_MIES_PR_MAJ,
            PREMIA_UZ_MIES_PR_CZERWIEC,
            PREMIA_UZ_MIES_PR_LIPIEC,
            PREMIA_UZ_MIES_PR_SIERPIEN,
            PREMIA_UZ_MIES_PR_WRZESIEN,
            PREMIA_UZ_MIES_PR_PAZDZIERNIK,
            PREMIA_UZ_MIES_PR_LISTOPAD,
            PREMIA_UZ_MIES_PR_GRUDZIEN,
            PREMIA_UZ_MIES_WA_STYCZEN,
            PREMIA_UZ_MIES_WA_LUTY,
            PREMIA_UZ_MIES_WA_MARZEC,
            PREMIA_UZ_MIES_WA_KWIECIEN,
            PREMIA_UZ_MIES_WA_MAJ,
            PREMIA_UZ_MIES_WA_CZERWIEC,
            PREMIA_UZ_MIES_WA_LIPIEC,
            PREMIA_UZ_MIES_WA_SIERPIEN,
            PREMIA_UZ_MIES_WA_WRZESIEN,
            PREMIA_UZ_MIES_WA_PAZDZIERNIK,
            PREMIA_UZ_MIES_WA_LISTOPAD,
            PREMIA_UZ_MIES_WA_GRUDZIEN,
            PREMIA_CAL_MIES_STY,
            PREMIA_CAL_MIES_LUT,
            PREMIA_CAL_MIES_MAR,
            PREMIA_CAL_MIES_KWI,
            PREMIA_CAL_MIES_MAI,
            PREMIA_CAL_MIES_CZE,
            PREMIA_CAL_MIES_LIP,
            PREMIA_CAL_MIES_SIE,
            PREMIA_CAL_MIES_WRZ,
            PREMIA_CAL_MIES_PAZ,
            PREMIA_CAL_MIES_LIS,
            PREMIA_CAL_MIES_GRU,
            PENSJA_CAL_MIES_STY,
            PENSJA_CAL_MIES_LUT,
            PENSJA_CAL_MIES_MAR,
            PENSJA_CAL_MIES_KWI,
            PENSJA_CAL_MIES_MAI,
            PENSJA_CAL_MIES_CZE,
            PENSJA_CAL_MIES_LIP,
            PENSJA_CAL_MIES_SIE,
            PENSJA_CAL_MIES_WRZ,
            PENSJA_CAL_MIES_PAZ,
            PENSJA_CAL_MIES_LIS,
            PENSJA_CAL_MIES_GRU,
        )VALUES(
            IMIE_STRING,
            NAZWISKO_STRING,
            PREMIA_MOTYWACYJNA_VALUE,
            PREMIA_UZN_MIES_PROC_STY_VAL,
            PREMIA_UZN_MIES_PROC_LUT_VAL,
            PREMIA_UZN_MIES_PROC_MAR_VAL,
            PREMIA_UZN_MIES_PROC_KWI_VAL,
            PREMIA_UZN_MIES_PROC_MAI_VAL,
            PREMIA_UZN_MIES_PROC_CZE_VAL,
            PREMIA_UZN_MIES_PROC_LIP_VAL,
            PREMIA_UZN_MIES_PROC_SIE_VAL,
            PREMIA_UZN_MIES_PROC_WRZ_VAL,
            PREMIA_UZN_MIES_PROC_PAZ_VAL,
            PREMIA_UZN_MIES_PROC_LIS_VAL,
            PREMIA_UZN_MIES_PROC_GRU_VAL,
            PREMIA_UZN_MIES_STY_VAL,
            PREMIA_UZN_MIES_LUT_VAL,
            PREMIA_UZN_MIES_MAR_VAL,
            PREMIA_UZN_MIES_KWI_VAL,
            PREMIA_UZN_MIES_MAI_VAL,
            PREMIA_UZN_MIES_CZE_VAL,
            PREMIA_UZN_MIES_LIP_VAL,
            PREMIA_UZN_MIES_SIE_VAL,
            PREMIA_UZN_MIES_WRZ_VAL,
            PREMIA_UZN_MIES_PAZ_VAL,
            PREMIA_UZN_MIES_LIS_VAL,
            PREMIA_UZN_MIES_GRU_VAL,
            PREMIA_CAL_MIES_STY_VAL,
            PREMIA_CAL_MIES_LUT_VAL,
            PREMIA_CAL_MIES_MAR_VAL,
            PREMIA_CAL_MIES_KWI_VAL,
            PREMIA_CAL_MIES_MAI_VAL,
            PREMIA_CAL_MIES_CZE_VAL,
            PREMIA_CAL_MIES_LIP_VAL,
            PREMIA_CAL_MIES_SIE_VAL,
            PREMIA_CAL_MIES_WRZ_VAL,
            PREMIA_CAL_MIES_PAZ_VAL,
            PREMIA_CAL_MIES_LIS_VAL,
            PREMIA_CAL_MIES_GRU_VAL,
            PENSJA_CAL_MIES_STY_VAL,
            PENSJA_CAL_MIES_LUT_VAL,
            PENSJA_CAL_MIES_MAR_VAL,
            PENSJA_CAL_MIES_KWI_VAL,
            PENSJA_CAL_MIES_MAI_VAL,
            PENSJA_CAL_MIES_CZE_VAL,
            PENSJA_CAL_MIES_LIP_VAL,
            PENSJA_CAL_MIES_SIE_VAL,
            PENSJA_CAL_MIES_WRZ_VAL,
            PENSJA_CAL_MIES_PAZ_VAL,
            PENSJA_CAL_MIES_LIS_VAL,
            PENSJA_CAL_MIES_GRU_VAL,
        )

END WYPELNIJ_LISTE_PLAC;

PROCEDURE WYCZYSC_LISTE
IS
BEGIN

TRUNCATE LISTA_PLAC;

END WYCZYSC_LISTE;

END PLACE;