CREATE OR REPLACE PACKAGE PLACE
IS

PROCEDURE WYPELNIJ_LISTE_PLAC;
PROCEDURE WYCZYSC_LISTE PLAC;
PROCEDURE DODAJ_PRACOWNIKA(IMIE_STRING VARCHAR(4), NAZWISKO_STRING VARCHAR(4), PENSJA_ZASADNICZA_VALUE NUMBER);

END PLACE;

CREATE OR REPLACE PACKAGE BODY place
AS

  PROCEDURE DODAJ_PRACOWNIKA(IMIE_STRING VARCHAR2, NAZWISKO_STRING VARCHAR2, PENSJA_ZASADNICZA_VALUE NUMBER);


    BEGIN


        PREMIA_MOTYWACYJNA_VALUE := (PENSJA_ZASADNICZA*10)/100;
        PREMIA_UZN_MIES_PROC_STY_VAL  := DBMS_RANDOM.VALUE(0, 20);
        PREMIA_UZN_MIES_PROC_LUT_VAL  := DBMS_RANDOM.VALUE(0, 20);
        PREMIA_UZN_MIES_PROC_MAR_VAL  := DBMS_RANDOM.VALUE(0, 20);
        PREMIA_UZN_MIES_PROC_KWI_VAL  := DBMS_RANDOM.VALUE(0, 20);
        PREMIA_UZN_MIES_PROC_MAI_VAL  := DBMS_RANDOM.VALUE(0, 20);
        PREMIA_UZN_MIES_PROC_CZE_VAL  := DBMS_RANDOM.VALUE(0, 20);
        PREMIA_UZN_MIES_PROC_LIP_VAL  := DBMS_RANDOM.VALUE(0, 20);
        PREMIA_UZN_MIES_PROC_SIE_VAL  := DBMS_RANDOM.VALUE(0, 20);
        PREMIA_UZN_MIES_PROC_WRZ_VAL  := DBMS_RANDOM.VALUE(0, 20);
        PREMIA_UZN_MIES_PROC_PAZ_VAL  := DBMS_RANDOM.VALUE(0, 20);
        PREMIA_UZN_MIES_PROC_LIS_VAL  := DBMS_RANDOM.VALUE(0, 20);
        PREMIA_UZN_MIES_PROC_GRU_VAL  := DBMS_RANDOM.VALUE(0, 20);
        PREMIA_UZN_MIES_STY_VAL  := ROUND((PENSJA_ZASADNICZA_VALUE * PREMIA_UZN_MIES_PROC_STY_VAL)/100);
        PREMIA_UZN_MIES_LUT_VAL  := ROUND((PENSJA_ZASADNICZA_VALUE * PREMIA_UZN_MIES_PROC_LUT_VAL)/100);
        PREMIA_UZN_MIES_MAR_VAL  := ROUND((PENSJA_ZASADNICZA_VALUE * PREMIA_UZN_MIES_PROC_MAR_VAL)/100);
        PREMIA_UZN_MIES_KWI_VAL  := ROUND((PENSJA_ZASADNICZA_VALUE * PREMIA_UZN_MIES_PROC_KWI_VAL)/100);
        PREMIA_UZN_MIES_MAI_VAL  := ROUND((PENSJA_ZASADNICZA_VALUE * PREMIA_UZN_MIES_PROC_MAI_VAL)/100);
        PREMIA_UZN_MIES_CZE_VAL  := ROUND((PENSJA_ZASADNICZA_VALUE * PREMIA_UZN_MIES_PROC_CZE_VAL)/100);
        PREMIA_UZN_MIES_LIP_VAL  := ROUND((PENSJA_ZASADNICZA_VALUE * PREMIA_UZN_MIES_PROC_LIP_VAL)/100);
        PREMIA_UZN_MIES_SIE_VAL  := ROUND((PENSJA_ZASADNICZA_VALUE * PREMIA_UZN_MIES_PROC_SIE_VAL)/100);
        PREMIA_UZN_MIES_WRZ_VAL  := ROUND((PENSJA_ZASADNICZA_VALUE * PREMIA_UZN_MIES_PROC_WRZ_VAL)/100);
        PREMIA_UZN_MIES_PAZ_VAL  := ROUND((PENSJA_ZASADNICZA_VALUE * PREMIA_UZN_MIES_PROC_PAZ_VAL)/100);
        PREMIA_UZN_MIES_LIS_VAL  := ROUND((PENSJA_ZASADNICZA_VALUE * PREMIA_UZN_MIES_PROC_LIS_VAL)/100);
        PREMIA_UZN_MIES_GRU_VAL  := ROUND((PENSJA_ZASADNICZA_VALUE * PREMIA_UZN_MIES_PROC_GRU_VAL)/100);
        PREMIA_CAL_MIES_STY_VAL  := PREMIA_MOTYWACYJNA_VALUE + PREMIA_UZN_MIES_STY_VAL;
        PREMIA_CAL_MIES_LUT_VAL  := PREMIA_MOTYWACYJNA_VALUE + PREMIA_UZN_MIES_LUT_VAL;
        PREMIA_CAL_MIES_MAR_VAL  := PREMIA_MOTYWACYJNA_VALUE + PREMIA_UZN_MIES_MAR_VAL;
        PREMIA_CAL_MIES_KWI_VAL  := PREMIA_MOTYWACYJNA_VALUE + PREMIA_UZN_MIES_KWI_VAL;
        PREMIA_CAL_MIES_MAI_VAL  := PREMIA_MOTYWACYJNA_VALUE + PREMIA_UZN_MIES_MAI_VAL;
        PREMIA_CAL_MIES_CZE_VAL  := PREMIA_MOTYWACYJNA_VALUE + PREMIA_UZN_MIES_CZE_VAL;
        PREMIA_CAL_MIES_LIP_VAL  := PREMIA_MOTYWACYJNA_VALUE + PREMIA_UZN_MIES_LIP_VAL;
        PREMIA_CAL_MIES_SIE_VAL  := PREMIA_MOTYWACYJNA_VALUE + PREMIA_UZN_MIES_SIE_VAL;
        PREMIA_CAL_MIES_WRZ_VAL  := PREMIA_MOTYWACYJNA_VALUE + PREMIA_UZN_MIES_WRZ_VAL;
        PREMIA_CAL_MIES_PAZ_VAL  := PREMIA_MOTYWACYJNA_VALUE + PREMIA_UZN_MIES_PAZ_VAL;
        PREMIA_CAL_MIES_LIS_VAL  := PREMIA_MOTYWACYJNA_VALUE + PREMIA_UZN_MIES_LIS_VAL;
        PREMIA_CAL_MIES_GRU_VAL  := PREMIA_MOTYWACYJNA_VALUE + PREMIA_UZN_MIES_GRU_VAL;
        PENSJA_CAL_MIES_STY_VAL  := PENSJA_ZASADNICZA_VALUE + PREMIA_CAL_MIES_STY_VAL;
        PENSJA_CAL_MIES_LUT_VAL  := PENSJA_ZASADNICZA_VALUE + PREMIA_CAL_MIES_LUT_VAL;
        PENSJA_CAL_MIES_MAR_VAL  := PENSJA_ZASADNICZA_VALUE + PREMIA_CAL_MIES_MAR_VAL;
        PENSJA_CAL_MIES_KWI_VAL  := PENSJA_ZASADNICZA_VALUE + PREMIA_CAL_MIES_KWI_VAL;
        PENSJA_CAL_MIES_MAI_VAL  := PENSJA_ZASADNICZA_VALUE + PREMIA_CAL_MIES_MAI_VAL;
        PENSJA_CAL_MIES_CZE_VAL  := PENSJA_ZASADNICZA_VALUE + PREMIA_CAL_MIES_CZE_VAL;
        PENSJA_CAL_MIES_LIP_VAL  := PENSJA_ZASADNICZA_VALUE + PREMIA_CAL_MIES_LIP_VAL;
        PENSJA_CAL_MIES_SIE_VAL  := PENSJA_ZASADNICZA_VALUE + PREMIA_CAL_MIES_SIE_VAL;
        PENSJA_CAL_MIES_WRZ_VAL  := PENSJA_ZASADNICZA_VALUE + PREMIA_CAL_MIES_WRZ_VAL;
        PENSJA_CAL_MIES_PAZ_VAL  := PENSJA_ZASADNICZA_VALUE + PREMIA_CAL_MIES_PAZ_VAL;
        PENSJA_CAL_MIES_LIS_VAL  := PENSJA_ZASADNICZA_VALUE + PREMIA_CAL_MIES_LIS_VAL;
        PENSJA_CAL_MIES_GRU_VAL  := PENSJA_ZASADNICZA_VALUE + PREMIA_CAL_MIES_GRU_VAL;

        INSERT INTO LISTA_PLAC(
            IMIE,
            NAZWISKO,
            PENSJA_ZASADNICZA,
            PREMIA_MOTYWACYJNA,
            PREMIA_UZ_MIES_PR_STYCZEN,
            PREMIA_UZ_MIES_PR_LUTY,
            PREMIA_UZ_MIES_PR_MARZEC,
            PREMIA_UZ_MIES_PR_KWIECIEN,
            PREMIA_UZ_MIES_PR_MAJ,
            PREMIA_UZ_MIES_PR_CZERWIEC,
            PREMIA_UZ_MIES_PR_LIPIEC,
            PREMIA_UZ_MIES_PR_SIERPIEN,
            PREMIA_UZ_MIES_PR_WRZESIEN,
            PREMIA_UZ_MIES_PR_PAZDZIERNIK,
            PREMIA_UZ_MIES_PR_LISTOPAD,
            PREMIA_UZ_MIES_PR_GRUDZIEN,
            PREMIA_UZ_MIES_WA_STYCZEN,
            PREMIA_UZ_MIES_WA_LUTY,
            PREMIA_UZ_MIES_WA_MARZEC,
            PREMIA_UZ_MIES_WA_KWIECIEN,
            PREMIA_UZ_MIES_WA_MAJ,
            PREMIA_UZ_MIES_WA_CZERWIEC,
            PREMIA_UZ_MIES_WA_LIPIEC,
            PREMIA_UZ_MIES_WA_SIERPIEN,
            PREMIA_UZ_MIES_WA_WRZESIEN,
            PREMIA_UZ_MIES_WA_PAZDZIERNIK,
            PREMIA_UZ_MIES_WA_LISTOPAD,
            PREMIA_UZ_MIES_WA_GRUDZIEN,
            PREMIA_CAL_MIES_STY,
            PREMIA_CAL_MIES_LUT,
            PREMIA_CAL_MIES_MAR,
            PREMIA_CAL_MIES_KWI,
            PREMIA_CAL_MIES_MAI,
            PREMIA_CAL_MIES_CZE,
            PREMIA_CAL_MIES_LIP,
            PREMIA_CAL_MIES_SIE,
            PREMIA_CAL_MIES_WRZ,
            PREMIA_CAL_MIES_PAZ,
            PREMIA_CAL_MIES_LIS,
            PREMIA_CAL_MIES_GRU,
            PENSJA_CAL_MIES_STY,
            PENSJA_CAL_MIES_LUT,
            PENSJA_CAL_MIES_MAR,
            PENSJA_CAL_MIES_KWI,
            PENSJA_CAL_MIES_MAI,
            PENSJA_CAL_MIES_CZE,
            PENSJA_CAL_MIES_LIP,
            PENSJA_CAL_MIES_SIE,
            PENSJA_CAL_MIES_WRZ,
            PENSJA_CAL_MIES_PAZ,
            PENSJA_CAL_MIES_LIS,
            PENSJA_CAL_MIES_GRU,
            PENSJA_MINIMALNA,
            PENSJA_MAKSYMALNA,
            PENSJA_SREDNIA,
            PREMIA_MINIMALNA,
            PREMIA_MAKSYMALNA,
            PREMIA_SREDNIA
        )VALUES(
            IMIE_STRING,
            NAZWISKO_STRING,
            PENSJA_ZASADNICZA_VALUE,
            PREMIA_MOTYWACYJNA_VALUE,
            PREMIA_UZN_MIES_PROC_STY_VAL,
            PREMIA_UZN_MIES_PROC_LUT_VAL,
            PREMIA_UZN_MIES_PROC_MAR_VAL,
            PREMIA_UZN_MIES_PROC_KWI_VAL,
            PREMIA_UZN_MIES_PROC_MAI_VAL,
            PREMIA_UZN_MIES_PROC_CZE_VAL,
            PREMIA_UZN_MIES_PROC_LIP_VAL,
            PREMIA_UZN_MIES_PROC_SIE_VAL,
            PREMIA_UZN_MIES_PROC_WRZ_VAL,
            PREMIA_UZN_MIES_PROC_PAZ_VAL,
            PREMIA_UZN_MIES_PROC_LIS_VAL,
            PREMIA_UZN_MIES_PROC_GRU_VAL,
            PREMIA_UZN_MIES_STY_VAL,
            PREMIA_UZN_MIES_LUT_VAL,
            PREMIA_UZN_MIES_MAR_VAL,
            PREMIA_UZN_MIES_KWI_VAL,
            PREMIA_UZN_MIES_MAI_VAL,
            PREMIA_UZN_MIES_CZE_VAL,
            PREMIA_UZN_MIES_LIP_VAL,
            PREMIA_UZN_MIES_SIE_VAL,
            PREMIA_UZN_MIES_WRZ_VAL,
            PREMIA_UZN_MIES_PAZ_VAL,
            PREMIA_UZN_MIES_LIS_VAL,
            PREMIA_UZN_MIES_GRU_VAL,
            PREMIA_CAL_MIES_STY_VAL,
            PREMIA_CAL_MIES_LUT_VAL,
            PREMIA_CAL_MIES_MAR_VAL,
            PREMIA_CAL_MIES_KWI_VAL,
            PREMIA_CAL_MIES_MAI_VAL,
            PREMIA_CAL_MIES_CZE_VAL,
            PREMIA_CAL_MIES_LIP_VAL,
            PREMIA_CAL_MIES_SIE_VAL,
            PREMIA_CAL_MIES_WRZ_VAL,
            PREMIA_CAL_MIES_PAZ_VAL,
            PREMIA_CAL_MIES_LIS_VAL,
            PREMIA_CAL_MIES_GRU_VAL,
            PENSJA_CAL_MIES_STY_VAL,
            PENSJA_CAL_MIES_LUT_VAL,
            PENSJA_CAL_MIES_MAR_VAL,
            PENSJA_CAL_MIES_KWI_VAL,
            PENSJA_CAL_MIES_MAI_VAL,
            PENSJA_CAL_MIES_CZE_VAL,
            PENSJA_CAL_MIES_LIP_VAL,
            PENSJA_CAL_MIES_SIE_VAL,
            PENSJA_CAL_MIES_WRZ_VAL,
            PENSJA_CAL_MIES_PAZ_VAL,
            PENSJA_CAL_MIES_LIS_VAL,
            PENSJA_CAL_MIES_GRU_VAL,
            3000,
            10000,
            4500,
            300,
            1000,
            700
        );

    END DODAJ_PRACOWNIKA;

  PROCEDURE WYPELNIJ_LISTE_PLAC
  IS
  BEGIN

    FOR i IN 1..10
    LOOP

        PENSJA_ZASADNICZA_VALUE := DBMS_RANDOM.VALUE(300, 1000) * 10;
        IMIE_STRING := DBMS_RANDOM.STRING('A', 4);
        NAZWISKO_STRING  := DBMS_RANDOM.STRING('A', 4);
        DODAJ_PRACOWNIKA(IMIE_STRING, NAZWISKO_STRING, PENSJA_ZASADNICZA_VALUE);
    END LOOP;

  END WYPELNIJ_LISTE_PLAC;

  PROCEDURE WYCZYSC_LISTE
  IS
  BEGIN

  TRUNCATE LISTA_PLAC;

  END WYCZYSC_LISTE;

END PLACE;
