CREATE OR REPLACE PACKAGE PLACE
IS
PROCEDURE WYPELNIJ_LISTE_PLAC;
PROCEDURE WYCZYSC_LISTE PLAC;
FUNCTION DAJ_LISTE_PLAC;
END PLACE;

CREATE OR REPLACE PACKAGE BODY PLACE
IS

PROCEDURE WYPELNIJ_LISTE_PLAC

DECLARE
    i NUMBER :=0;
BEGIN

    LOOP
        i := i+1;
        DECLARE PENSJA_ZASADNICZA_VALUE NUMBER := DBMS_RANDOM.VALUE(3000,10000)
        EXIT WHEN i=10

END WYPELNIJ_LISTE_PLAC;

END PLACE;